apiVersion: v2
name: deploy-charts
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: "producer"
    condition: producer.enabled
  - name: "watcher"
    condition: watcher.enabled
  - name: "workflow"
    condition: workflow.enabled
  - name: "postgresdb"
    condition: postgresdb.enabled
